version: '1.0'
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - raft-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8081:8081"
    networks:
        - raft-network

  node3:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8082:8082"
      networks:
        - raft-network

  node4:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
          - "8083:8083"
      networks:
          - raft-network

  node5:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
          - "8083:8083"
      networks:
          - raft-network


networks:
  raft-network:
    driver: bridge