services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=0
      - PORT=50051
    networks:
      - raft-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=1
      - PORT=50052
    networks:
        - raft-network

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=2
      - PORT=50053
    networks:
      - raft-network



networks:
  raft-network:
    driver: bridge